# Generated by Django 3.2.5 on 2022-03-06 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trombinoscoop', '0002_auto_20220221_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='faculty',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Trombinoscoop.faculty'),
        ),
    ]
