# Generated by Django 3.2.5 on 2022-03-06 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trombinoscoop', '0005_remove_person_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='friends',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Trombinoscoop.person'),
        ),
    ]
