# Generated by Django 3.2.5 on 2022-03-06 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trombinoscoop', '0006_person_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='friends',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Trombinoscoop.person'),
        ),
    ]
