# Generated by Django 3.2.5 on 2022-03-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trombinoscoop', '0008_alter_person_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='friends',
        ),
        migrations.AddField(
            model_name='person',
            name='friends',
            field=models.ManyToManyField(related_name='_Trombinoscoop_person_friends_+', to='Trombinoscoop.Person'),
        ),
    ]
