# Generated by Django 4.1.3 on 2023-08-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trombinoscoop', '0009_auto_20220306_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='friends',
            field=models.ManyToManyField(to='Trombinoscoop.person'),
        ),
    ]
